# escape=`
FROM sixeyed/msbuild:netfx-4.5.2-ssdt AS builder




SHELL ["powershell"]
CMD ["ls"]
# WORKDIR C:\src\SignUp.Database
# COPY src\SignUp.Database .
# RUN msbuild SignUp.Database.sqlproj `
#     /p:SQLDBExtensionsRefPath="C:\Microsoft.Data.Tools.Msbuild.10.0.61026\lib\net40" `
#     /p:SqlServerRedistPath="C:\Microsoft.Data.Tools.Msbuild.10.0.61026\lib\net40"